Download binaries rather than building from source
holochain-apps/holochain-kangaroo pull request #20
Opened 2024-08-13 11:33 UTC by c12i

2024-08-13 12:14 UTC, matthme requested changes
It looks great but I think the binaries should now also be given executable permissions after fetching (`chmod +x`) because they by default don't have executable permissions if not built locally.

2024-08-20 08:56 UTC, c12i commented
@matthme ready for review. Sorry for blowing up the PR, added some quality of life improvements and re-organized some of the rust modules for easier access. Hopefully this is not a hinderance.

2024-08-20 09:24 UTC, c12i commented on README.md
> -1. Install [Rust](https://www.rust-lang.org/tools/install) and [Go](https://go.dev/doc/install) (Go is required for Holochain version 0.2.X). Then follow the [Tauri Prerequisites](https://tauri.app/v
Not sure, I went off the fact that `Go` was only required for holochain `0.2.x`, is it still needed to compile `lair` and `holochain`? Also, we are no longer having to compile the binaries anymore since we download the binaries via holochainBinaries, so I didn't think `Go` was needed anymore. Correct me if I am wrong though.

2024-08-20 09:33 UTC, matthme commented on README.md
> -1. Install [Rust](https://www.rust-lang.org/tools/install) and [Go](https://go.dev/doc/install) (Go is required for Holochain version 0.2.X). Then follow the [Tauri Prerequisites](https://tauri.app/v
It is still needed for holochain 0.3 and 0.4 to compile holochain itself (not lair though I think). But I'm not sure about compiling kangaroo if the binaries themselves have been fetched independently.

2024-08-20 09:34 UTC, matthme commented on .github/workflows/release-codesigned.yaml
> +          cargo install --version 0.4.5 lair_keystore
I think we can now actually replace these steps with running the new `install_binaries.sh` script everywhere in these workflows, right?

2024-08-20 09:37 UTC, matthme commented on package.json
> +  "name": "forum",
I think this one should be reverted to "replace-me" so that it shows up in search-and-replace when following the readme instructions.

2024-08-20 09:38 UTC, c12i commented on package.json
> +  "name": "forum",
Good catch, should remove these.

2024-08-20 09:39 UTC, matthme commented on src-tauri/tauri.conf.json
> -    "productName": "replace-me",
same here and with the indentifier below.

2024-08-20 09:43 UTC, matthme commented on pouch/forum.happ
And we should probably remove these binary files again (the .happ and the ui.zip) although it's handy for testing...

2024-08-20 09:51 UTC, matthme commented on src-tauri/src/initialization_scripts/signZomeCall.js
Maybe we could just add a one-liner comment on top of this file pointing to its source in the hc-launch repository (permanent github link)?

2024-08-20 11:31 UTC, c12i commented on src-tauri/src/initialization_scripts/signZomeCall.js
Good idea, would would ideally want to download this script at build time though, will do this in a separate PR

2024-08-20 11:49 UTC, c12i commented on README.md
> -1. Install [Rust](https://www.rust-lang.org/tools/install) and [Go](https://go.dev/doc/install) (Go is required for Holochain version 0.2.X). Then follow the [Tauri Prerequisites](https://tauri.app/v
Build succeeded in CI, I think this shouldn't be a hard requirement anymore since we don't compile holochain anymore.

2024-08-20 12:23 UTC, matthme approved these changes
Great work! Good to merge I think.

2024-08-20 12:34 UTC, merged